[package]
name = "wf-hub"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
iced = { version = "0.14.0", features = ["tokio", "advanced", "image", "svg"] }
include_dir = "0.7.4"
notify-rust = "4.17.0"
reqwest = { version = "0.13.3", features = ["json"] }
rodio = "0.22.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
worldstate_parser = { git = "https://github.com/WFCD/worldstate_parser_rs", version = "0.1.0" }

[build-dependencies]
embed-resource = "2.5"
